/**
 * Turns approved products into publish-ready ones, on the server, without anyone asking.
 *
 * Approving used to set a flag and stop there: artwork had to be generated by hand on the operator's
 * machine, so an approved product sat with no images until somebody remembered — and the publish ticker
 * would happily send it to Etsy image-less. For a product other people pay for, "the operator runs a
 * Python script" is not a pipeline.
 *
 * The work itself lives in scripts/produce_product.py, which the agent's `produce` tool and the operator
 * also call. One implementation, three callers: a second path that builds listing images is the exact
 * defect that once shipped a whole catalogue at the wrong scale.
 */
import { spawn } from "child_process";
import path from "path";
import { q, one, logEvent } from "./db";

const SCRIPT = path.join(process.cwd(), "scripts", "produce_product.py");

/**
 * Claim one product atomically.
 *
 * `design_state` is the claim: NULL/'error' means free, 'generating' means taken. The UPDATE ... WHERE
 * design_state IS NULL is the lock, so two ticks (or a tick and the agent) cannot pick the same row —
 * without that, both would spend a Higgsfield call on the same design and one would overwrite the other.
 */
async function claim(): Promise<{ id: number; slug: string; priorState: string | null } | null> {
  // The prior state has to come out of the claim itself. RETURNING gives the row AFTER the update, so it
  // always reads 'generating' and the caller cannot tell a redo from a first run — which is exactly how
  // redo silently stopped redrawing: the script skips generation when a print file already exists, and it
  // only clears one when it is passed --redo. A row asking for a redraw got its images rebuilt from the
  // old artwork instead, at no visible error.
  const rows = await q<any>(
    `WITH picked AS (
        SELECT p.id, p.design_state AS prior_state FROM products p
         WHERE p.content_status = 'approved'
           -- 'ready' with no images belongs here too. It is a contradiction — the artwork exists and
           -- the listing has nothing to show — and until now no loop resolved it: the producer only
           -- claimed NULL or 'redo', so four approved products sat unreachable, one of them scheduled
           -- to publish and certain to fail because Etsy requires an image. The print file is already
           -- there, so this pass only rebuilds the mockups.
           AND (p.design_state IS NULL OR p.design_state = 'redo'
                OR (p.design_state = 'ready'
                    AND NOT EXISTS (SELECT 1 FROM product_images g2
                                     WHERE g2.product_id = p.id
                                       AND coalesce(g2.role,'') <> 'cover_unstamped')))
           AND p.design_prompt IS NOT NULL
           -- No hook check. A wordless design is the default, not a defect: the operator's standing
           -- instruction (2026-08-20) is that nothing carries a slogan unless they asked for one, and a
           -- required hook field is exactly what made the agent invent phrases — an anime portrait went
           -- out captioned "CHERRY ANIME". The gate's real concern, that the garment pick lived behind
           -- the hook check in set_type, is fixed there: a wordless row picks its garment too.
           AND NOT EXISTS (SELECT 1 FROM product_images g WHERE g.product_id = p.id)
         ORDER BY p.id
         LIMIT 1
         FOR UPDATE SKIP LOCKED)
     UPDATE products SET design_state = 'generating', updated_at = now()
       FROM picked WHERE products.id = picked.id
      RETURNING products.id, products.slug, picked.prior_state AS "priorState"`);
  return rows[0] ?? null;
}

function run(pid: number, redo = false, stage: "all" | "artwork" | "finish" = "all"): Promise<{ ok: boolean; out: string }> {
  return new Promise((resolve) => {
    // A generation is one Higgsfield call plus seven composites: minutes, not seconds. The timeout is
    // generous but present, because a hung child would hold the claim for ever.
    const stageArg = stage === "artwork" ? ["--artwork"] : stage === "finish" ? ["--finish"] : [];
    const child = spawn("python3", [SCRIPT, String(pid), ...(redo ? ["--redo"] : []), ...stageArg], {
      // 5 minutes, not 15. The agent runs this inline inside an 800s request, so a 15-minute child could
      // outlive the request that is waiting on it and take the transcript write down with it. A generation
      // that has not finished in five minutes is hung, not slow.
      env: process.env, timeout: 5 * 60_000,
    });
    let out = "";
    child.stdout.on("data", (d) => { out += d.toString(); });
    child.stderr.on("data", (d) => { out += d.toString(); });
    child.on("close", (code) => resolve({ ok: code === 0, out: out.trim().slice(-500) }));
    child.on("error", (e) => resolve({ ok: false, out: String(e).slice(0, 300) }));
  });
}

/** One pass: produce up to `max` approved products that have no images yet. */
export async function produceDue(max = 1): Promise<{ produced: number; failed: number }> {
  let produced = 0;
  let failed = 0;
  for (let i = 0; i < max; i++) {
    const item = await claim();
    if (!item) break;
    // A row that asked for a redo needs the artwork drawn again, not its images rebuilt from the old one.
    const res = await run(item.id, item.priorState === "redo");
    if (res.ok) {
      produced++;
      await logEvent("produce_ok", { detail: `${item.slug}: ${res.out.slice(-160)}` });
    } else {
      failed++;
      // Park it as 'error', never back to NULL: a design that fails deterministically (an empty prompt,
      // a missing blank) would otherwise be retried every minute and burn a paid call each time.
      await q(`UPDATE products SET design_state='error', redo_note=$2, updated_at=now() WHERE id=$1`,
              [item.id, res.out.slice(-400)]);
      await logEvent("produce_fail", { detail: `${item.slug}: ${res.out.slice(-200)}` });
      console.error(`[producer] ${item.slug} basarisiz: ${res.out.slice(-200)}`);
    }
  }
  return { produced, failed };
}

/**
 * Produce ONE named product, for the agent tool and for a manual retry.
 *
 * It re-checks eligibility itself rather than trusting the caller: the agent picks the id from a SELECT
 * it ran earlier, and by the time the tool runs the row may already be claimed by the scheduler.
 */
export async function produceOne(productId: number, stage: "all" | "artwork" = "all"): Promise<{ ok: boolean; out: string }> {
  const rows = await q<any>(
    `WITH picked AS (
        SELECT id, design_state AS prior_state FROM products
         WHERE id = $1 AND content_status = 'approved' AND design_prompt IS NOT NULL
           AND (design_state IS NULL OR design_state IN ('redo', 'error'))
         FOR UPDATE)
     UPDATE products SET design_state='generating', updated_at=now()
       FROM picked WHERE products.id = picked.id
      RETURNING products.id, products.slug, picked.prior_state AS "priorState"`, [productId]);
  if (!rows.length) {
    // Say WHICH condition failed. The old message listed all of them as questions, so the agent could not
    // tell "not approved" from "already produced" — watched live it guessed, forced design_state='redo'
    // with raw SQL and produced the same product four times at a paid call each.
    const cur = await one<any>(
      `SELECT content_status, design_state, design_prompt IS NOT NULL AS has_prompt,
              (SELECT count(*)::int FROM product_images g WHERE g.product_id = p.id) AS images
         FROM products p WHERE id = $1`, [productId]);
    if (!cur) return { ok: false, out: `urun ${productId} yok` };
    const why = cur.content_status !== "approved"
      ? `content_status='${cur.content_status}' — onaylanmadan uretilmez`
      : !cur.has_prompt
        ? "design_prompt bos — once konsept yazilmali"
        : cur.design_state === "generating"
          ? "baska bir islem su an bu urunu uretiyor"
          : cur.design_state === "ready"
            ? `zaten uretilmis (${cur.images} gorsel). Yeniden uretmek icin design_state='redo' yap ve `
              + "redo_note'a NEYIN degisecegini yaz — aksi halde ayni sonucu tekrar odersin`"
            : `design_state='${cur.design_state}' uygun degil`;
    return { ok: false, out: why };
  }

  // A wordless design is allowed. This used to REFUSE one, because the style tails reserve a band for the
  // caption and a design with no caption ships with an empty panel. That was a real defect but the wrong
  // remedy: asked three times for a design with no text, the gate blocked it three times and the agent got
  // past it by writing a slogan into the row that nobody wanted. The reservation is dropped at the prompt
  // instead (batch_runner.style_tail with_text=False), so wordless produces a full-bleed design.
  const pre = await one<any>(
    `SELECT technique, coalesce(btrim(hook), '') AS hook FROM products WHERE id = $1`, [productId]);
  const wordless = Boolean(pre) && pre.technique !== "embroidery" && !pre.hook;
  // 'redo'/'error' rows already carry a print file; without --redo the script would skip generation and
  // only rebuild images from the old artwork.
  const res = await run(productId, rows[0].priorState === "redo" || rows[0].priorState === "error");
  if (res.ok) {
    await logEvent("produce_ok",
                   { detail: `${rows[0].slug}${wordless ? " (yazisiz)" : ""}: ${res.out.slice(-160)}` });
  } else {
    await q(`UPDATE products SET design_state='error', redo_note=$2, updated_at=now() WHERE id=$1`,
            [productId, res.out.slice(-400)]);
    await logEvent("produce_fail", { detail: `${rows[0].slug}: ${res.out.slice(-200)}` });
  }
  return res;
}

/** Take a design past the approval gate: build the remaining frames and mark it ready.
 *
 * Deliberately not routed through produceOne. That function's job is to CLAIM unproduced work, so its guard
 * refuses anything already in flight — including a design sitting at 'awaiting_approval', which is exactly
 * what this is for. The claim here is the operator's decision.
 */
export async function finishApproved(productId: number): Promise<{ ok: boolean; out: string }> {
  const row = await one<{ slug: string; design_state: string | null }>(
    `SELECT slug, design_state FROM products WHERE id = $1`, [productId]);
  if (!row) return { ok: false, out: `urun ${productId} yok` };
  if (row.design_state !== "awaiting_approval") {
    return { ok: false, out: `design_state='${row.design_state}' — onay bekleyen bir tasarim degil` };
  }
  const res = await run(productId, false, "finish");
  if (res.ok) {
    await logEvent("design_approved", { productId, detail: `${row.slug}: tam set kuruldu` });
  } else {
    await q(`UPDATE products SET design_state='error', redo_note=$2, updated_at=now() WHERE id=$1`,
            [productId, res.out.slice(-400)]);
  }
  return res;
}

/** Reject a design. The preview stays so the operator can still see what was turned down, and the reason
 *  is stored where the next generation reads it. */
export async function rejectDesign(productId: number, note: string): Promise<{ ok: boolean }> {
  await q(`UPDATE products SET design_state='rejected', redo_note=$2, updated_at=now() WHERE id=$1`,
          [productId, note.slice(0, 400) || "operator reddetti"]);
  await logEvent("design_rejected", { productId, detail: note.slice(0, 200) || "sebep verilmedi" });
  return { ok: true };
}
