/**
 * Turns approved products into publish-ready ones, on the server, without anyone asking.
 *
 * Approving used to set a flag and stop there: artwork had to be generated by hand on the operator's
 * machine, so an approved product sat with no images until somebody remembered — and the publish ticker
 * would happily send it to Etsy image-less. For a product other people pay for, "the operator runs a
 * Python script" is not a pipeline.
 *
 * The work itself lives in scripts/produce_product.py, which the agent's `produce` tool and the operator
 * also call. One implementation, three callers: a second path that builds listing images is the exact
 * defect that once shipped a whole catalogue at the wrong scale.
 */
import { spawn } from "child_process";
import path from "path";
import { q, logEvent } from "./db";

const SCRIPT = path.join(process.cwd(), "scripts", "produce_product.py");

/**
 * Claim one product atomically.
 *
 * `design_state` is the claim: NULL/'error' means free, 'generating' means taken. The UPDATE ... WHERE
 * design_state IS NULL is the lock, so two ticks (or a tick and the agent) cannot pick the same row —
 * without that, both would spend a Higgsfield call on the same design and one would overwrite the other.
 */
async function claim(): Promise<{ id: number; slug: string } | null> {
  const rows = await q<any>(
    `UPDATE products SET design_state = 'generating', updated_at = now()
      WHERE id = (
        SELECT p.id FROM products p
         WHERE p.content_status = 'approved'
           AND (p.design_state IS NULL OR p.design_state = 'redo')
           AND p.design_prompt IS NOT NULL
           AND NOT EXISTS (SELECT 1 FROM product_images g WHERE g.product_id = p.id)
         ORDER BY p.id
         LIMIT 1
         FOR UPDATE SKIP LOCKED)
      RETURNING id, slug`);
  return rows[0] ?? null;
}

function run(pid: number): Promise<{ ok: boolean; out: string }> {
  return new Promise((resolve) => {
    // A generation is one Higgsfield call plus seven composites: minutes, not seconds. The timeout is
    // generous but present, because a hung child would hold the claim for ever.
    const child = spawn("python3", [SCRIPT, String(pid)], {
      env: process.env, timeout: 15 * 60_000,
    });
    let out = "";
    child.stdout.on("data", (d) => { out += d.toString(); });
    child.stderr.on("data", (d) => { out += d.toString(); });
    child.on("close", (code) => resolve({ ok: code === 0, out: out.trim().slice(-500) }));
    child.on("error", (e) => resolve({ ok: false, out: String(e).slice(0, 300) }));
  });
}

/** One pass: produce up to `max` approved products that have no images yet. */
export async function produceDue(max = 1): Promise<{ produced: number; failed: number }> {
  let produced = 0;
  let failed = 0;
  for (let i = 0; i < max; i++) {
    const item = await claim();
    if (!item) break;
    const res = await run(item.id);
    if (res.ok) {
      produced++;
      await logEvent("produce_ok", { detail: `${item.slug}: ${res.out.slice(-160)}` });
    } else {
      failed++;
      // Park it as 'error', never back to NULL: a design that fails deterministically (an empty prompt,
      // a missing blank) would otherwise be retried every minute and burn a paid call each time.
      await q(`UPDATE products SET design_state='error', redo_note=$2, updated_at=now() WHERE id=$1`,
              [item.id, res.out.slice(-400)]);
      await logEvent("produce_fail", { detail: `${item.slug}: ${res.out.slice(-200)}` });
      console.error(`[producer] ${item.slug} basarisiz: ${res.out.slice(-200)}`);
    }
  }
  return { produced, failed };
}

/**
 * Produce ONE named product, for the agent tool and for a manual retry.
 *
 * It re-checks eligibility itself rather than trusting the caller: the agent picks the id from a SELECT
 * it ran earlier, and by the time the tool runs the row may already be claimed by the scheduler.
 */
export async function produceOne(productId: number): Promise<{ ok: boolean; out: string }> {
  const rows = await q<any>(
    `UPDATE products SET design_state='generating', updated_at=now()
      WHERE id = $1 AND content_status = 'approved' AND design_prompt IS NOT NULL
        AND (design_state IS NULL OR design_state IN ('redo', 'error'))
      RETURNING id, slug`, [productId]);
  if (!rows.length) {
    return { ok: false, out: "uygun degil: onayli mi, promptu var mi, baska bir islem tarafindan alinmis mi?" };
  }
  const res = await run(productId);
  if (res.ok) {
    await logEvent("produce_ok", { detail: `${rows[0].slug}: ${res.out.slice(-160)}` });
  } else {
    await q(`UPDATE products SET design_state='error', redo_note=$2, updated_at=now() WHERE id=$1`,
            [productId, res.out.slice(-400)]);
    await logEvent("produce_fail", { detail: `${rows[0].slug}: ${res.out.slice(-200)}` });
  }
  return res;
}
