/**
 * Turns approved products into publish-ready ones, on the server, without anyone asking.
 *
 * Approving used to set a flag and stop there: artwork had to be generated by hand on the operator's
 * machine, so an approved product sat with no images until somebody remembered — and the publish ticker
 * would happily send it to Etsy image-less. For a product other people pay for, "the operator runs a
 * Python script" is not a pipeline.
 *
 * The work itself lives in scripts/produce_product.py, which the agent's `produce` tool and the operator
 * also call. One implementation, three callers: a second path that builds listing images is the exact
 * defect that once shipped a whole catalogue at the wrong scale.
 */
import { spawn } from "child_process";
import path from "path";
import { q, one, logEvent } from "./db";

const SCRIPT = path.join(process.cwd(), "scripts", "produce_product.py");

/**
 * Claim one product atomically.
 *
 * `design_state` is the claim: NULL/'error' means free, 'generating' means taken. The UPDATE ... WHERE
 * design_state IS NULL is the lock, so two ticks (or a tick and the agent) cannot pick the same row —
 * without that, both would spend a Higgsfield call on the same design and one would overwrite the other.
 */
async function claim(): Promise<{ id: number; slug: string; priorState: string | null } | null> {
  // The prior state has to come out of the claim itself. RETURNING gives the row AFTER the update, so it
  // always reads 'generating' and the caller cannot tell a redo from a first run — which is exactly how
  // redo silently stopped redrawing: the script skips generation when a print file already exists, and it
  // only clears one when it is passed --redo. A row asking for a redraw got its images rebuilt from the
  // old artwork instead, at no visible error.
  const rows = await q<any>(
    `WITH picked AS (
        SELECT p.id, p.design_state AS prior_state FROM products p
         WHERE p.content_status = 'approved'
           AND (p.design_state IS NULL OR p.design_state = 'redo')
           AND p.design_prompt IS NOT NULL
           -- A DTF row with no hook produces a wordless design and skips the measured garment pick.
           -- produceOne refuses such a row outright; the queue must agree rather than quietly paying for
           -- the weak version. These surface via production_status.wordless_no_hook.
           AND (p.technique = 'embroidery' OR coalesce(btrim(p.hook), '') <> '')
           AND NOT EXISTS (SELECT 1 FROM product_images g WHERE g.product_id = p.id)
         ORDER BY p.id
         LIMIT 1
         FOR UPDATE SKIP LOCKED)
     UPDATE products SET design_state = 'generating', updated_at = now()
       FROM picked WHERE products.id = picked.id
      RETURNING products.id, products.slug, picked.prior_state AS "priorState"`);
  return rows[0] ?? null;
}

function run(pid: number, redo = false): Promise<{ ok: boolean; out: string }> {
  return new Promise((resolve) => {
    // A generation is one Higgsfield call plus seven composites: minutes, not seconds. The timeout is
    // generous but present, because a hung child would hold the claim for ever.
    const child = spawn("python3", [SCRIPT, String(pid), ...(redo ? ["--redo"] : [])], {
      env: process.env, timeout: 15 * 60_000,
    });
    let out = "";
    child.stdout.on("data", (d) => { out += d.toString(); });
    child.stderr.on("data", (d) => { out += d.toString(); });
    child.on("close", (code) => resolve({ ok: code === 0, out: out.trim().slice(-500) }));
    child.on("error", (e) => resolve({ ok: false, out: String(e).slice(0, 300) }));
  });
}

/** One pass: produce up to `max` approved products that have no images yet. */
export async function produceDue(max = 1): Promise<{ produced: number; failed: number }> {
  let produced = 0;
  let failed = 0;
  for (let i = 0; i < max; i++) {
    const item = await claim();
    if (!item) break;
    // A row that asked for a redo needs the artwork drawn again, not its images rebuilt from the old one.
    const res = await run(item.id, item.priorState === "redo");
    if (res.ok) {
      produced++;
      await logEvent("produce_ok", { detail: `${item.slug}: ${res.out.slice(-160)}` });
    } else {
      failed++;
      // Park it as 'error', never back to NULL: a design that fails deterministically (an empty prompt,
      // a missing blank) would otherwise be retried every minute and burn a paid call each time.
      await q(`UPDATE products SET design_state='error', redo_note=$2, updated_at=now() WHERE id=$1`,
              [item.id, res.out.slice(-400)]);
      await logEvent("produce_fail", { detail: `${item.slug}: ${res.out.slice(-200)}` });
      console.error(`[producer] ${item.slug} basarisiz: ${res.out.slice(-200)}`);
    }
  }
  return { produced, failed };
}

/**
 * Produce ONE named product, for the agent tool and for a manual retry.
 *
 * It re-checks eligibility itself rather than trusting the caller: the agent picks the id from a SELECT
 * it ran earlier, and by the time the tool runs the row may already be claimed by the scheduler.
 */
export async function produceOne(productId: number): Promise<{ ok: boolean; out: string }> {
  const rows = await q<any>(
    `WITH picked AS (
        SELECT id, design_state AS prior_state FROM products
         WHERE id = $1 AND content_status = 'approved' AND design_prompt IS NOT NULL
           AND (design_state IS NULL OR design_state IN ('redo', 'error'))
         FOR UPDATE)
     UPDATE products SET design_state='generating', updated_at=now()
       FROM picked WHERE products.id = picked.id
      RETURNING products.id, products.slug, picked.prior_state AS "priorState"`, [productId]);
  if (!rows.length) {
    // Say WHICH condition failed. The old message listed all of them as questions, so the agent could not
    // tell "not approved" from "already produced" — watched live it guessed, forced design_state='redo'
    // with raw SQL and produced the same product four times at a paid call each.
    const cur = await one<any>(
      `SELECT content_status, design_state, design_prompt IS NOT NULL AS has_prompt,
              (SELECT count(*)::int FROM product_images g WHERE g.product_id = p.id) AS images
         FROM products p WHERE id = $1`, [productId]);
    if (!cur) return { ok: false, out: `urun ${productId} yok` };
    const why = cur.content_status !== "approved"
      ? `content_status='${cur.content_status}' — onaylanmadan uretilmez`
      : !cur.has_prompt
        ? "design_prompt bos — once konsept yazilmali"
        : cur.design_state === "generating"
          ? "baska bir islem su an bu urunu uretiyor"
          : cur.design_state === "ready"
            ? `zaten uretilmis (${cur.images} gorsel). Yeniden uretmek icin design_state='redo' yap ve `
              + "redo_note'a NEYIN degisecegini yaz — aksi halde ayni sonucu tekrar odersin`"
            : `design_state='${cur.design_state}' uygun degil`;
    return { ok: false, out: why };
  }

  // A DTF design with no hook is the empty-banner failure waiting to happen: the prompt reserves a text
  // zone, nothing is typeset into it, and the tee ships with a blank ribbon. Cheaper to say so before the
  // paid call than to redo it — which is exactly what happened four times to one product.
  const pre = await one<any>(
    `SELECT technique, coalesce(btrim(hook), '') AS hook FROM products WHERE id = $1`, [productId]);
  if (pre && pre.technique !== "embroidery" && !pre.hook) {
    await q(`UPDATE products SET design_state=NULL, updated_at=now() WHERE id=$1`, [productId]);
    return { ok: false, out: "hook bos — bu tasarimda yazi olmaz ve sablon bos serit birakir. "
      + "Once hook'a sloganini yaz (kazananlarin neredeyse hepsinde yazi var), sonra uret." };
  }
  // 'redo'/'error' rows already carry a print file; without --redo the script would skip generation and
  // only rebuild images from the old artwork.
  const res = await run(productId, rows[0].priorState === "redo" || rows[0].priorState === "error");
  if (res.ok) {
    await logEvent("produce_ok", { detail: `${rows[0].slug}: ${res.out.slice(-160)}` });
  } else {
    await q(`UPDATE products SET design_state='error', redo_note=$2, updated_at=now() WHERE id=$1`,
            [productId, res.out.slice(-400)]);
    await logEvent("produce_fail", { detail: `${rows[0].slug}: ${res.out.slice(-200)}` });
  }
  return res;
}
