#!/usr/bin/env python3
"""Take one approved product from copy to publish-ready images. The ONE entrypoint for that.

    python3 scripts/produce_product.py <product_id>

Approving a product used to change a flag and nothing else: the artwork had to be generated by hand on
the operator's machine, so an approved product sat with `design_state=NULL` and no images until somebody
remembered. The agent could not do it either — there was no path, only a prompt line saying so. For a
product other people pay for, that is not a gap in automation, it is the absence of the product.

This script is called by three callers and does the same thing for all of them, deliberately: the
scheduler's producer tick, the agent's `produce` tool, and the operator on a terminal. Two paths that
both build a listing image is exactly the defect that shipped a whole catalogue at the wrong scale.

Steps, all resumable — anything already done is skipped, so a re-run after a crash costs nothing:
  1. design    Higgsfield generates the artwork from products.design_prompt (the paid step, ~$0.03)
  2. cutout    background keyed locally, transparent pixels decontaminated (free)
  3. palette   embroidery only: colours snapped to the declared thread hexes
  4. print_file written to the DB, which is what the digitiser and the compositor read
  5. images    scripts/produce_images.py builds the 7-9 listing frames
  6. ready     design_state='ready'
"""
from __future__ import annotations

import io
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import psycopg2
from PIL import Image

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import batch_runner as br                                      # noqa: E402
from joblog import Job                                         # noqa: E402
import typeset                                                 # noqa: E402


def conn():
    return psycopg2.connect(os.environ["DATABASE_URL"], connect_timeout=25,
                            keepalives=1, keepalives_idle=20)


def load(pid: int) -> dict:
    c = conn(); k = c.cursor()
    k.execute("""SELECT id, slug, shop_id, technique, design_prompt, thread_colors,
                        (print_file IS NOT NULL) AS has_print,
                        (SELECT count(*) FROM product_images g WHERE g.product_id = p.id) AS images,
                        design_state, content_status, design_params, hook, hero_colorway
                   FROM products p WHERE id = %s""", (pid,))
    row = k.fetchone()
    c.close()
    if not row:
        sys.exit(f"urun {pid} yok")
    cols = ["id", "slug", "shop_id", "technique", "design_prompt", "thread_colors",
            "has_print", "images", "design_state", "content_status", "design_params",
            "hook", "hero_colorway"]
    d = dict(zip(cols, row))
    if isinstance(d.get("design_params"), str):
        try:
            d["design_params"] = json.loads(d["design_params"])
        except (json.JSONDecodeError, TypeError):
            d["design_params"] = {}
    return d


def generate(p: dict, work: Path) -> Path:
    """The paid step. Prompt comes from the row, so what was approved is what gets drawn."""
    raw = work / f"{p['slug']}-raw.png"
    if raw.exists():
        return raw
    prompt = (p["design_prompt"] or "").strip()
    if not prompt:
        raise RuntimeError("design_prompt bos — once konsept yazilmali")
    emb = p["technique"] == "embroidery"
    # Reuse the batch pipeline's prompt tail and thread-palette clause rather than restating them: the
    # rules about flat colour, transparent background and "NO text" live in one place.
    pal = br.palette_line(p["thread_colors"]) if emb else ""
    lead = br.EMB_PROMPT_CLAUSE if emb else ""
    # design_params.style carries the chosen look; the tail comes from the same table batch_runner uses.
    style = (p.get("design_params") or {}).get("style") if isinstance(p.get("design_params"), dict) else None
    # The stored prompt is a FULL prompt from an earlier batch, tail included. Appending a new tail to it
    # asked for flat vector and fine engraving at once; `subject_of` keeps the concept (and its own palette)
    # and drops the old style block.
    subject, has_palette = br.subject_of(prompt)
    if subject:
        # Whoever wrote the concept does not get to choose the background. One product's prompt said
        # "isolated on a plain solid uniform background" and never named a colour; the subject was nine
        # WHITE ducks, the generator picked white, and the cutout had nothing to key on. The pipeline names
        # the colour, so any background sentence in the concept is removed first — leaving both would be a
        # contradiction resolved at random.
        subject = br.strip_background_talk(subject)
        # The artifact contract leads: what the file IS, before any description of what is in it.
        full = (f"{br.ARTIFACT_CONTRACT}. {subject.rstrip(',')}, {lead}{pal}"
                f"{br.style_tail(style, with_palette=not has_palette, subject=subject)}")
    else:
        # The legacy prompt could not be reduced to a subject. Use it unchanged — it produced something
        # coherent before — and say out loud that this product needs its concept rewritten to get the new look.
        # Even an unconvertible legacy prompt gets the key colour: it is what makes the file cuttable.
        full = f"{br.strip_background_talk(prompt)}, {br.key_clause()}"
        print(f"UYARI {p['slug']}: eski prompt yeni stile cevrilemedi, konu oldugu gibi kullanildi — "
              f"konsept yeniden yazilmali", file=sys.stderr)
    # 2k generated a 2048 px source, and after keying that is a 205 PPI print file — a fifth short of the
    # 300 PPI the producer prints at. 4k comes back near 4096, which the cutout resamples DOWN to exactly
    # 3000: supersampled rather than stretched, so the resolution is real.
    #
    # A square canvas is a default, not a decision. Forced on a wide or tall concept it squeezes the design
    # and leaves most of the 10 inch envelope empty, so a concept may declare its natural shape and the
    # generator is asked for that instead.
    params = p.get("design_params") or {}
    ratio = params.get("aspect_ratio") if isinstance(params, dict) else None
    out = br.hf({"op": "generate", "prompt": full, "out": str(raw), "aspect_ratio": ratio or "1:1",
                 "model": br.DEFAULT_MODEL, "quality": br.DEFAULT_QUALITY, "resolution": "4k"},
                shop_id=p["shop_id"])
    if not out.get("ok"):
        raise RuntimeError(f"higgsfield: {out.get('error')}")
    return raw


def cutout(p: dict, raw: Path, work: Path) -> Path:
    final = work / f"{p['slug']}-final.png"
    if final.exists():
        return final
    # Key on the colour the prompt demanded, then CHECK it. A background that survived the cut is the one
    # defect that reaches the customer as visible dirt, and it is cheap to detect: the key colour cannot
    # legitimately appear in the artwork, so any of it left over means the generator drifted and the file
    # must not ship.
    cut, rep = br.key_cutout(raw, work / f"{p['slug']}-cutout.png")
    print(f"  kesim: opak %{rep['opaque_frac']*100:.1f}, zemin %{rep['bg_frac']*100:.1f}, "
          f"kalan anahtar piksel {rep['leftover_key_px']}, kenar temasi %{rep['edge_contact']*100:.1f}, "
          f"300 PPI'da {rep['size_in_at_300']} inc", file=sys.stderr)
    if rep["bg_frac"] < 0.15:
        raise RuntimeError(
            f"anahtar renk zemin bulunamadi (zemin %{rep['bg_frac']*100:.1f}) — generator istenen "
            f"{br.KEY_COLOR} arka plani cizmemis; prompt/urun kontrol edilmeli")
    if rep["leftover_key_px"] > 200:
        raise RuntimeError(f"kesimden sonra {rep['leftover_key_px']} anahtar renk pikseli kaldi — "
                           "zemin temizlenemedi, dosya yayina verilmez")
    if not 0.03 <= rep["opaque_frac"] <= 0.95:
        raise RuntimeError(f"opak alan %{rep['opaque_frac']*100:.1f} — tasarim ya kayboldu ya zemin kaldi")
    # Artwork on the border means the composition ran off the canvas. It is invisible in the raw frame and
    # unmissable on a tee, where a wing or a boot ends in a straight cut. Same treatment as a failed cut:
    # the caller regenerates once. 2% tolerates the odd anti-aliased pixel; 30 shipped files measure 0.
    if rep["edge_contact"] > 0.02:
        raise RuntimeError(f"tasarim kenara degiyor (%{rep['edge_contact']*100:.1f}) — kompozisyon "
                           "canvas disina tasmis, kirpilmis dosya baskiya verilmez")
    # Not fatal: a short file still prints, just softer. Say it out loud rather than shipping quietly under
    # standard, because nothing downstream measures this again.
    if rep["size_in_at_300"] < br.PRINT_MIN_IN:
        print(f"  UYARI dosya 300 PPI'da yalnizca {rep['size_in_at_300']} inc basilabilir "
              f"({br.PRINT_MIN_IN} inc tabaninin altinda) — daha buyuk uretilmeli", file=sys.stderr)
    if p["technique"] == "embroidery" and p["thread_colors"]:
        br.stage_palette_snap(cut, br.hexes(p["thread_colors"]), final)
    else:
        final.write_bytes(Path(cut).read_bytes())
    return final


# Example values for the placeholders a personalised hook carries. 67 hooks hold tokens like {SURNAME} or
# {GRADE}, and a listing image is the one place they must NOT appear literally: 22 products once shipped
# reading "[Name]'S DAD". The buyer's real value is set per order; the listing shows a plausible example so
# they can see what they are buying.
EXAMPLES = {
    "NAME": "EMMA", "NAMES": "EMMA, NOAH & MIA", "NAME1": "EMMA", "NAME2": "NOAH",
    "SURNAME": "MILLER", "YEAR": "2026", "GRADE": "2ND GRADE", "ROOM": "12",
    "TEACHERNAME": "MRS. HAYES", "PETNAME": "BISCUIT", "SUBJECT": "SCIENCE",
}
PLACEHOLDER = re.compile(r"[{\[]([^}\]]+)[}\]]")


def fill_placeholders(text: str) -> str:
    """Swap {TOKEN} for an example. An unknown token becomes a neutral word rather than braces on a shirt."""
    return PLACEHOLDER.sub(lambda m: EXAMPLES.get(m.group(1).strip().upper(), "YOURS"), text)


def pick_garment(art_path: Path) -> tuple[str, str, float]:
    """Choose the hero garment for this artwork, and the ink the type must be set in.

    Returns (colourway, ink hex). The garment is whichever model blank the artwork reads most strongly
    against; the ink is then simply the opposite end of the scale from that garment.
    """
    import numpy as np
    c = conn(); k = c.cursor()
    k.execute("SELECT colorway, bytes FROM mockup_blanks WHERE name = ANY(%s)",
              (["model-IvoryTrendy4", "model-Pepper"],))
    blanks = [(cw, Image.open(io.BytesIO(bytes(b))).convert("L")) for cw, b in k.fetchall()]
    c.close()
    a = np.asarray(Image.open(art_path).convert("RGBA"))
    m = a[:, :, 3] > 128
    if not m.any() or not blanks:
        return "Ivory", "#2B2B2B", 247.0
    ink_lum = float((0.2126 * a[:, :, 0] + 0.7152 * a[:, :, 1] + 0.0722 * a[:, :, 2])[m].mean())
    best = max(blanks, key=lambda t: abs(ink_lum - float(np.asarray(t[1]).mean())))
    garment_lum = float(np.asarray(best[1]).mean())
    ink = "#F2E8D5" if garment_lum < 128 else "#2B2B2B"
    print(f"  garment {best[0]} secildi (tasarim {ink_lum:.0f}, kumas {garment_lum:.0f}); "
          f"yazi {ink}", file=sys.stderr)
    return best[0], ink, garment_lum


def dominant_ink(art_path: Path) -> str:
    """The artwork's own main ink colour, for the caption to be set in.

    The winners set the caption in the SAME colour as the illustration: cream type under a cream engraving,
    dark type under a dark one. Deciding from median luminance failed on exactly the style we now default to
    — an engraving is cream fills over dark hatching, so the median reads "dark" while the design reads
    light, and the caption came out invisible on the garment the artwork needs. Taking the most common
    colour instead follows the artwork rather than an average of it.
    """
    import numpy as np
    a = np.asarray(Image.open(art_path).convert("RGBA"))
    m = a[:, :, 3] > 200
    if not m.any():
        return "#2B2B2B"
    px = a[:, :, :3][m]
    # Quantise so near-identical inks count as one, and ignore the thin outline black that borders
    # everything: it is structure, not the design's colour.
    q = (px // 24) * 24
    lum = 0.2126 * q[:, 0] + 0.7152 * q[:, 1] + 0.0722 * q[:, 2]
    keep = q[(lum > 28) & (lum < 250)]
    if not len(keep):
        keep = q
    colours, counts = np.unique(keep, axis=0, return_counts=True)
    r, g, b = colours[counts.argmax()]
    # Nudge toward the warm cream / charcoal the shop prints, so type stays in the house palette.
    return "#F2E8D5" if (0.2126 * r + 0.7152 * g + 0.0722 * b) > 150 else "#2B2B2B"


def set_type(p: dict, art_path: Path, work: Path) -> Path:
    """Hand-set the product's phrase onto the artwork.

    Every design that sells carries words, and ours went out as wordless emblems. The model never draws
    letters — it returns malformed glyphs — so the phrase is set here in real type, in the layout its
    style calls for (serif caption under an engraving, arched title over a character, poster stack).

    The ink follows the ARTWORK, not the stored hero colourway. That ordering matters: the garment is
    chosen later, by measured contrast against this same artwork, so a cream-forward engraving will end up
    on a dark tee. Reading `hero_colorway` here would have set dark type for the Ivory in the row and then
    put it on the Pepper the contrast rule picks — invisible text on a listing that looked finished.
    Matching the artwork's own ink keeps the two decisions consistent whichever garment wins.
    """
    hook = (p.get("hook") or "").strip()
    if not hook:
        return art_path                      # a wordless design is valid, just weaker
    hook = fill_placeholders(hook)
    style = (p.get("design_params") or {}).get("style") if isinstance(p.get("design_params"), dict) else None

    garment, ink, garment_lum = pick_garment(art_path)
    # Record it now so produce_images features the same garment the type was set for.
    c = conn(); k = c.cursor()
    k.execute("UPDATE products SET hero_colorway=%s WHERE id=%s", (garment, p["id"]))
    c.commit(); c.close()

    out = work / f"{p['slug']}-typed.png"
    canvas, drawn, type_mask = typeset.compose(Image.open(art_path), hook,
                                               style=style or "engraving", ink=ink)
    if not drawn:
        return art_path

    # Measure what was actually drawn, not what was asked for. A product shipped with a dark caption on a
    # Pepper hero — unreadable — while the log for that very run reported cream ink. I could not reproduce
    # the divergence (typeset honours the ink it is given, verified both ways), so this checks the OUTPUT
    # instead of trusting the decision: if the caption does not separate from the garment it will sit on,
    # set it again in the opposite ink and say so.
    canvas, ink = _ensure_readable(canvas, type_mask, art_path, hook, style, ink, garment_lum)

    canvas.save(out)
    print(f"  yazi dizildi: {drawn} satir, murekkep {ink}", file=sys.stderr)
    return out


def _caption_lum(canvas: Image.Image, type_mask: Image.Image) -> float | None:
    """Mean luminance of the type, measured through the mask typeset drew it with."""
    import numpy as np
    a = np.asarray(canvas.convert("RGBA")).astype(float)
    m = np.asarray(type_mask) > 128
    if m.sum() < 200:                         # no measurable type: nothing to judge
        return None
    return float((0.2126 * a[:, :, 0] + 0.7152 * a[:, :, 1] + 0.0722 * a[:, :, 2])[m].mean())


def _ensure_readable(canvas: Image.Image, type_mask: Image.Image, art_path: Path, hook: str,
                     style: str | None, ink: str, garment_lum: float,
                     floor: float = 100.0) -> tuple[Image.Image, str]:
    """Re-set the type in the opposite ink when it would not read on the chosen garment.

    The floor is 100, not the ~60 a pure luminance difference would suggest. Dark type on Pepper measures
    a difference of 84 and is still unreadable on the finished mockup: the compositor multiplies the ink by
    the garment's shading and lays it at 0.94 opacity, and thin serif strokes lose far more separation than
    a flat tone comparison predicts — this is the exact case that shipped an invisible caption.

    With only two hero blanks (Ivory 247, Pepper 127) this floor reduces to a rule the pipeline already
    intends: dark garment gets cream type, light garment gets dark. So the gate adds no new policy — it
    catches any path that produced something else, which is what happened and what I could not reproduce.
    """
    lum = _caption_lum(canvas, type_mask)
    if lum is None:
        return canvas, ink
    contrast = abs(lum - garment_lum)
    if contrast >= floor:
        return canvas, ink
    flipped = "#2B2B2B" if garment_lum >= 128 else "#F2E8D5"
    print(f"  UYARI yazi kumasa karsi okunmuyor (yazi {lum:.0f} vs kumas {garment_lum:.0f}, "
          f"kontrast {contrast:.0f} < {floor:.0f}) — murekkep {flipped} ile tekrar diziliyor",
          file=sys.stderr)
    again, _, _ = typeset.compose(Image.open(art_path), hook, style=style or "engraving", ink=flipped)
    return again, flipped


def store_print_file(p: dict, art: Path) -> None:
    blob = art.read_bytes()
    w, h = Image.open(art).size
    c = conn(); k = c.cursor()
    k.execute("""UPDATE products SET print_file=%s, print_file_name=%s, print_file_w=%s,
                        print_file_h=%s, design_state='generating', updated_at=now()
                  WHERE id=%s""",
              (psycopg2.Binary(blob), f"{p['slug']}-print.png", w, h, p["id"]))
    c.commit(); c.close()


def build_images(pid: int, only_cover: bool = False) -> int:
    cmd = [sys.executable, str(HERE / "produce_images.py"), str(pid)]
    if only_cover:
        cmd.append("--only-cover")
    r = subprocess.run(cmd,
                       capture_output=True, text=True)
    last = (r.stdout or r.stderr or "").strip().splitlines()[-1:] or [""]
    try:
        out = json.loads(last[0])
    except json.JSONDecodeError:
        raise RuntimeError(f"produce_images: {last[0][:200]}")
    if not out.get("ok"):
        raise RuntimeError(f"produce_images: {last[0][:200]}")
    return int(out.get("images", 0))


def set_state(pid: int, state: str) -> None:
    c = conn(); k = c.cursor()
    k.execute("UPDATE products SET design_state=%s, updated_at=now() WHERE id=%s", (state, pid))
    c.commit(); c.close()


def mark_ready(pid: int) -> None:
    c = conn(); k = c.cursor()
    k.execute("UPDATE products SET design_state='ready', updated_at=now() WHERE id=%s", (pid,))
    c.commit(); c.close()


def produce(pid: int, redo: bool = False, stage: str = "all") -> dict:
    """Build (or rebuild) one product's artwork and listing images.

    `redo` clears the existing print file and images so the design is drawn again — and it does that HERE,
    after the approval check, on purpose. Callers used to clear first and then invoke this, which meant an
    unapproved product had its artwork deleted and then the refusal arrived: nine draft products lost their
    print file and every listing image that way, with nothing left to rebuild from. The destructive step
    belongs behind the guard that decides whether the work can happen at all.
    """
    p = load(pid)
    if p["content_status"] != "approved":
        return {"ok": False, "slug": p["slug"], "error": f"content_status={p['content_status']}, onayli degil"}
    if redo:
        c = conn(); k = c.cursor()
        k.execute("""UPDATE products SET print_file=NULL, design_state=NULL, redo_note=NULL
                      WHERE id=%s""", (pid,))
        k.execute("DELETE FROM product_images WHERE product_id=%s", (pid,))
        c.commit(); c.close()
        p = load(pid)                     # has_print is now false; generate from scratch

    with Job("design", f"{p['slug']} · tasarim + gorseller", total=3, shop_id=p["shop_id"],
             product_id=pid) as job:
        with tempfile.TemporaryDirectory(prefix=f"prod-{p['slug']}-") as tmp:
            work = Path(tmp)
            if not p["has_print"]:
                # The generator honours the key colour most of the time, not every time — measured, it
                # painted magenta on one attempt and something else on another with the same prompt. A
                # stochastic miss should cost a second call, not the operator's afternoon, so the gate's
                # verdict drives one retry before it becomes an error.
                art = None
                for attempt in (1, 2):
                    raw = generate(p, work)
                    job.tick("tasarim uretildi" if attempt == 1 else "tasarim tekrar uretildi")
                    try:
                        art = cutout(p, raw, work)
                        break
                    except RuntimeError as e:
                        if attempt == 2:
                            raise
                        print(f"  UYARI kesim reddetti ({e}); bir kez daha uretiliyor", file=sys.stderr)
                        raw.unlink(missing_ok=True)
                        (work / f"{p['slug']}-cutout.png").unlink(missing_ok=True)
                job.tick("arka plan temizlendi")
                # Embroidery is typeset by the generator, not by us. print_file for an embroidery
                # product is the digitiser's spec — flat colour, exact thread hexes — and its hook is a
                # descriptive sentence ("a stone dice tower crowned as a guild badge"), not a slogan.
                # Laying PIL type over it would hand the factory a paragraph to stitch, and the listing
                # would never show it either: the gallery composites emb_render, not print_file.
                if p["technique"] != "embroidery":
                    art = set_type(p, art, work)
                else:
                    print("  nakis: yazi dizilmedi (print_file dijitizasyon spesifikasyonu)", file=sys.stderr)
                store_print_file(p, art)
            else:
                job.tick("print_file zaten var")
                job.tick("arka plan atlandi")
            # Two stages, because approval is worth money. "artwork" stops at a design the operator can
            # look at — the print file plus a lead shot and a close crop, about twenty seconds of
            # compositing. "finish" buys the other eight frames and the schedule slot, and only runs on
            # something a human said yes to. Producing thirty designs to the end and asking afterwards is
            # how a rejected style costs half an hour of composites.
            if stage == "artwork":
                n = build_images(pid, only_cover=True)
                job.tick(f"{n} onizleme gorseli")
                set_state(pid, "awaiting_approval")
                return {"ok": True, "slug": p["slug"], "images": n, "stage": "artwork",
                        "state": "awaiting_approval"}
            n = build_images(pid)
            job.tick(f"{n} ilan gorseli")
    mark_ready(pid)
    return {"ok": True, "slug": p["slug"], "images": n}


def main() -> None:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    redo = "--redo" in sys.argv
    stage = "artwork" if "--artwork" in sys.argv else "finish" if "--finish" in sys.argv else "all"
    if not args:
        sys.exit("kullanim: produce_product.py <product_id> [--redo] [--artwork|--finish]")
    try:
        print(json.dumps(produce(int(args[0]), redo=redo, stage=stage), ensure_ascii=False))
    except Exception as e:
        # The caller is a loop or a chat tool; both need the reason as data, not a traceback.
        print(json.dumps({"ok": False, "error": f"{type(e).__name__}: {e}"[:300]}, ensure_ascii=False))
        sys.exit(1)


if __name__ == "__main__":
    main()
