#!/usr/bin/env python3
"""Take one approved product from copy to publish-ready images. The ONE entrypoint for that.

    python3 scripts/produce_product.py <product_id>

Approving a product used to change a flag and nothing else: the artwork had to be generated by hand on
the operator's machine, so an approved product sat with `design_state=NULL` and no images until somebody
remembered. The agent could not do it either — there was no path, only a prompt line saying so. For a
product other people pay for, that is not a gap in automation, it is the absence of the product.

This script is called by three callers and does the same thing for all of them, deliberately: the
scheduler's producer tick, the agent's `produce` tool, and the operator on a terminal. Two paths that
both build a listing image is exactly the defect that shipped a whole catalogue at the wrong scale.

Steps, all resumable — anything already done is skipped, so a re-run after a crash costs nothing:
  1. design    Higgsfield generates the artwork from products.design_prompt (the paid step, ~$0.03)
  2. cutout    background keyed locally, transparent pixels decontaminated (free)
  3. palette   embroidery only: colours snapped to the declared thread hexes
  4. print_file written to the DB, which is what the digitiser and the compositor read
  5. images    scripts/produce_images.py builds the 7-9 listing frames
  6. ready     design_state='ready'
"""
from __future__ import annotations

import io
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import psycopg2
from PIL import Image

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import batch_runner as br                                      # noqa: E402
from joblog import Job                                         # noqa: E402
import typeset                                                 # noqa: E402
import design_feedback                                        # noqa: E402
import design_score                                           # noqa: E402
import produce_images as pi_mod                               # noqa: E402

# How many candidates to draw before choosing. 1 keeps the old behaviour and the old bill.
BEST_OF = max(1, int(os.environ.get("DESIGN_BEST_OF", "1")))
# The only blanks a NEW embroidery product may use. Everything currently embroidered is a Comfort Colors
# 1717 t-shirt (23) or a Yupoong dad hat (14) and none of them is a sweatshirt, so this refuses all of
# today's shapes by design — that is the decision, not an oversight.
EMB_OK = re.compile(r"sweat|crewneck|hoodie", re.I)
# For a retry pass over concepts ALREADY KNOWN to put magenta in the artwork: narrow the keying tolerance
# from the first draw instead of paying for one doomed wide-tolerance attempt first.
HARD_MODE = os.environ.get("DESIGN_HARD_MODE") == "1"


def conn():
    return psycopg2.connect(os.environ["DATABASE_URL"], connect_timeout=25,
                            keepalives=1, keepalives_idle=20)


def load(pid: int) -> dict:
    c = conn(); k = c.cursor()
    k.execute("""SELECT id, slug, shop_id, technique, design_prompt, thread_colors,
                        (print_file IS NOT NULL) AS has_print,
                        (SELECT count(*) FROM product_images g WHERE g.product_id = p.id) AS images,
                        design_state, content_status, design_params, hook, hero_colorway, blank
                   FROM products p WHERE id = %s""", (pid,))
    row = k.fetchone()
    c.close()
    if not row:
        sys.exit(f"urun {pid} yok")
    cols = ["id", "slug", "shop_id", "technique", "design_prompt", "thread_colors",
            "has_print", "images", "design_state", "content_status", "design_params",
            "hook", "hero_colorway", "blank"]
    d = dict(zip(cols, row))
    if isinstance(d.get("design_params"), str):
        try:
            d["design_params"] = json.loads(d["design_params"])
        except (json.JSONDecodeError, TypeError):
            d["design_params"] = {}
    return d


# What to say on the SECOND attempt. The generic palette clause already asks for no magenta and the model
# still reaches for it — measured across a 97-product migration, roughly one in six came back with magenta
# INSIDE the artwork, which the cut then punches holes through. That rate went up when the palette moved
# from "two to five muted colours" to "six to twelve colourful ones": telling a model to be colourful
# makes it reach for the one hue this pipeline cannot allow. A repeat of the same prompt repeats the same
# mistake, so the retry says it louder and names the substitutes.
# ABANDONED, kept as a record. Two attempts were made to talk the model out of putting magenta in the
# drawing while keeping the magenta background it is required to paint. Both destroyed the background:
# the first said "no magenta anywhere in the artwork" and got bg_frac 0.0 on five of five products; the
# second spelled out "(1) the background is REQUIRED ... (2) the drawing must contain no magenta" and got
# bg_frac 0.0 on three of five. A colour cannot be simultaneously mandatory and forbidden in one prompt —
# the model collapses the distinction whichever way it is worded, and each rewrite cost five paid draws.
#
# What actually works is mechanical, not rhetorical: redraw (the generator is stochastic, and a clean
# draw is the common case) and narrow the keying tolerance so the flat background still keys while a
# coral or warm red in the drawing no longer falls inside the band.
REINFORCE = ""


def generate(p: dict, work: Path, reinforce: bool = False, tag: str = "") -> Path:
    """The paid step. Prompt comes from the row, so what was approved is what gets drawn."""
    raw = work / f"{p['slug']}{('-' + tag) if tag else ''}-raw.png"
    # Which engine drew is written beside the file, because resuming is the normal case here — a re-run
    # returns the existing raw without generating, and without this the cutout would pick its method
    # from an unset field and key a magenta background that is not there.
    stamp = raw.with_suffix(".engine")
    if raw.exists():
        if stamp.exists():
            p["_engine"] = stamp.read_text().strip()
        return raw
    prompt = (p["design_prompt"] or "").strip()
    if not prompt:
        raise RuntimeError("design_prompt bos — once konsept yazilmali")
    emb = p["technique"] == "embroidery"
    # Reuse the batch pipeline's prompt tail and thread-palette clause rather than restating them: the
    # rules about flat colour, transparent background and "NO text" live in one place.
    pal = br.palette_line(p["thread_colors"]) if emb else ""
    lead = br.EMB_PROMPT_CLAUSE if emb else ""
    # design_params.style carries the chosen look; the tail comes from the same table batch_runner uses.
    style = (p.get("design_params") or {}).get("style") if isinstance(p.get("design_params"), dict) else None
    has_hook = bool((p.get("hook") or "").strip())
    # The stored prompt is a FULL prompt from an earlier batch, tail included. Appending a new tail to it
    # asked for flat vector and fine engraving at once; `subject_of` keeps the concept (and its own palette)
    # and drops the old style block.
    # Refuse before spending. The cut keys on magenta, so artwork that asks for magenta is punched full of
    # holes by the step that is supposed to clean it — measured as `holes_px` after the fact, but the fact
    # costs a generation. 36 catalogue concepts name pink or magenta in their own palette.
    # Checked on the SUBJECT, not the raw prompt: every stored prompt names the magenta BACKGROUND, which
    # is the pipeline's own instruction and exactly what is supposed to be there. Running the check on the
    # raw text refused every product in the catalogue for the one magenta that is correct.
    bad_hue = br.concept_uses_key_hue(br.strip_background_talk(prompt))
    if bad_hue:
        raise RuntimeError(
            f"konsept paletinde '{bad_hue}' var — kesim anahtar rengi ({br.KEY_COLOR}) magenta oldugu icin "
            f"bu renk tasarimdan KESILIR ve delik acar. design_prompt'tan pembeyi/magentayi cikar "
            f"(mercan, kiremit, mor ya da sicak kirmizi kullan) ve tekrar dene.")
    subject, has_palette = br.subject_of(prompt)
    if subject:
        # Whoever wrote the concept does not get to choose the background. One product's prompt said
        # "isolated on a plain solid uniform background" and never named a colour; the subject was nine
        # WHITE ducks, the generator picked white, and the cutout had nothing to key on. The pipeline names
        # the colour, so any background sentence in the concept is removed first — leaving both would be a
        # contradiction resolved at random.
        subject = br.strip_background_talk(subject)
        # No hook means no words, so the concept's own "leave a blank headline area" instruction has to go
        # too — otherwise it argues with FILL_CLAUSE in the same prompt and the model draws the empty box.
        if not has_hook:
            subject = br.strip_caption_talk(subject)
        # The artifact contract leads: what the file IS, before any description of what is in it. Unless the
        # stored concept already carries it — whoever wrote that prompt was told to send the concept only, and
        # prepending a second copy is the same duplication that once put two style orders in one prompt.
        head = "" if br.ARTIFACT_MARK in subject.lower() else f"{br.ARTIFACT_CONTRACT}. "
        # No hook means no words, so the style must not reserve a band for them — otherwise the design ships
        # with an empty panel where a caption was going to go, which is the defect that used to make the
        # pipeline refuse wordless designs outright.
        # The real placement, not the style's guess. print_placement() is the same resolver the compositor
        # uses, so the prompt and the mockup now read one number instead of disagreeing by construction.
        from produce_images import print_placement
        dp = p.get("design_params") if isinstance(p.get("design_params"), dict) else {}
        spot = print_placement(dp)
        tail = br.style_tail(style, with_palette=not has_palette, subject=subject, with_text=has_hook,
                             print_in=spot.get("inches"), placement=spot.get("spot"),
                             palette=dp.get("palette"))
        full = f"{head}{subject.rstrip(',')}, {lead}{pal}{tail}"
    else:
        # The legacy prompt could not be reduced to a subject. Use it unchanged — it produced something
        # coherent before — and say out loud that this product needs its concept rewritten to get the new look.
        # Even an unconvertible legacy prompt gets the key colour: it is what makes the file cuttable.
        # PROMPT_TAIL_COMMON goes on even here. It is the ONLY place the prompt says NO text, NO letters,
        # NO words — and this branch used to omit it, so an unconvertible concept was the one path on which
        # the model was free to render its own malformed lettering. That breaks a non-negotiable (all type
        # is hand-set in a licensed font) and falsifies the provenance archive, which claims AI never sets
        # type here. A fallback may lose style; it may not lose a rule.
        full = (f"{br.strip_background_talk(prompt)}, {br.PROMPT_TAIL_COMMON}, {br.key_clause()}")
        print(f"UYARI {p['slug']}: eski prompt yeni stile cevrilemedi, konu oldugu gibi kullanildi — "
              f"konsept yeniden yazilmali", file=sys.stderr)
    # 2k generated a 2048 px source, and after keying that is a 205 PPI print file — a fifth short of the
    # 300 PPI the producer prints at. 4k comes back near 4096, which the cutout resamples DOWN to exactly
    # 3000: supersampled rather than stretched, so the resolution is real.
    #
    # A square canvas is a default, not a decision. Forced on a wide or tall concept it squeezes the design
    # and leaves most of the 10 inch envelope empty, so a concept may declare its natural shape and the
    # generator is asked for that instead.
    params = p.get("design_params") or {}
    from produce_images import as_params                          # noqa: PLC0415
    ratio = as_params(params).get("aspect_ratio")
    if reinforce and REINFORCE:
        full = f"{full}{REINFORCE}"
    # ---- which engine draws ----
    #
    # One call site, two possible engines. The local path is a feature behind LOCAL_ENGINE, which
    # defaults to `off` and restores byte-identical behaviour when it is; the hosted path below is
    # never deleted and is also where a local failure lands.
    #
    # Falling back is deliberately quiet for the product — a design still gets drawn — and loud in the
    # record, because "how much work is local actually carrying" is unanswerable afterwards otherwise.
    import image_engine as ie                                     # noqa: PLC0415
    local, why = ie.use_local(p.get("id"))
    if local:
        try:
            info = ie.generate_local(full, raw, aspect=ratio or "1:1", product_id=p.get("id"))
            # Carried, not judged, here: the refusal belongs beside the other gates in cutout(), where
            # a rejection is labelled and turns into another candidate rather than a fallback to a paid
            # engine. Drawing letters is a bad draw, not a broken machine.
            p["_text_found"] = info.get("text_found")
            p["_engine"] = "local-comfyui"
            stamp.write_text("local-comfyui")
            print(f"  yerel uretim: {info['model']} · seed {info['seed']} · {info['seconds']}s")
            _record_engine(p, info)
            return raw
        except Exception as e:
            why = f"{type(e).__name__}: {e}"[:200]
            print(f"  UYARI yerel uretim dustu, Higgsfield'a geciliyor — {why}")

    p["_engine"] = "higgsfield"
    stamp.write_text("higgsfield")
    out = br.hf({"op": "generate", "prompt": full, "out": str(raw), "aspect_ratio": ratio or "1:1",
                 "model": br.DEFAULT_MODEL, "quality": br.DEFAULT_QUALITY, "resolution": "4k"},
                shop_id=p["shop_id"])
    if not out.get("ok"):
        raise RuntimeError(f"higgsfield: {out.get('error')}")
    _record_engine(p, {"engine": "higgsfield", "model": br.DEFAULT_MODEL,
                       "licence": "hosted", "fallback_reason": why or None})
    return raw


def _record_engine(p: dict, info: dict) -> None:
    """Write which engine drew, into the same table the design gates already use.

    Provenance is a publish gate here, not a log line: a design cannot go live without being able to
    name what drew it. A local model is the first setup that can state the checkpoint, licence and
    seed exactly rather than approximately, and that is worth capturing at the moment it happens.
    """
    try:
        import psycopg2, json as _j, os as _os                    # noqa: PLC0415
        c = psycopg2.connect(_os.environ["DATABASE_URL"], connect_timeout=20)
        k = c.cursor()
        k.execute("""INSERT INTO design_feedback (product_id, shop_id, source, verdict, reason,
                                                  metrics, design_model)
                     VALUES (%s,%s,'pipeline','accepted',%s,%s,%s)""",
                  (p.get("id"), p.get("shop_id"), info.get("fallback_reason"),
                   _j.dumps(info), info.get("model")))
        c.commit(); c.close()
    except Exception as e:
        print(f"  UYARI motor kaydi yazilamadi: {e}")


# How far from the key colour still counts as background. 60 is generous, which is right when the artwork
# genuinely contains no pink — it swallows the whole blend ring. It stopped being right when the palette
# became colourful: measured over a 97-product migration, a quarter of generations put SOME pink in the
# drawing, and at tol=60 a coral or a warm red accent falls inside the band and gets punched out as a
# hole. The background itself is drawn flat at exactly #E6007E, so a tight tolerance still keys it
# perfectly. Second attempt narrows the band rather than repeating the same cut and hoping.
TOL_WIDE, TOL_TIGHT = 60, 30


def _already_matted(raw: Path) -> bool:
    """Did this image arrive with its background already removed?

    Measured, not assumed: an older worker, a resumed run from before the change, or the Higgsfield
    fallback all produce a fully opaque file, and calling the no-rembg path on one of those would
    hand the gates an uncut image with a spotless report. Three percent fully-transparent is far below
    anything a real cutout leaves and far above the stray transparent pixel of an opaque render.
    """
    from PIL import Image                                          # noqa: PLC0415
    import numpy as _np                                            # noqa: PLC0415
    im = Image.open(raw)
    if im.mode not in ("RGBA", "LA"):
        return False
    a = _np.asarray(im.convert("RGBA"))[:, :, 3]
    return float((a == 0).sum()) / (a.size or 1) > 0.03


def _drawn_locally(p: dict) -> bool:
    """Did the local engine draw this one? Read from the row the process is already carrying.

    This used to ask the database and read back what generate() had just written, which is a round
    trip for a fact held in memory — and it failed closed twice on check constraints, so the cutout
    quietly used the key-colour method on an image that had no key colour in it.
    """
    return p.get("_engine") == "local-comfyui"


def cutout(p: dict, raw: Path, work: Path, tol: int = TOL_WIDE, attempt: int = 1,
           tag: str = "") -> Path:
    # Each candidate needs its own files or the second draw silently reuses the first — the `if
    # final.exists(): return final` resumability that makes a re-run cheap would make best-of-N a lie.
    final = work / f"{p['slug']}{('-' + tag) if tag else ''}-final.png"
    if final.exists():
        return final
    # Key on the colour the prompt demanded, then CHECK it. A background that survived the cut is the one
    # defect that reaches the customer as visible dirt, and it is cheap to detect: the key colour cannot
    # legitimately appear in the artwork, so any of it left over means the generator drifted and the file
    # must not ship.
    cut_to = work / f"{p['slug']}{('-' + tag) if tag else ''}-cutout.png"
    if _drawn_locally(p):
        # rembg, not the key colour. The local model will not paint the flat #E6007E field the key
        # cutout keys on, so keying it produces either "no background found" or a punched-through
        # emblem.
        #
        # WHERE it runs moved on 2026-08-19. The worker on the Spark now mattes its own output before
        # putting it on the queue, so what arrives here already carries alpha and only needs
        # thresholding and measuring — both pure PIL. The web container never had rembg and did not
        # need it while Higgsfield painted a key colour; turning the local engine on made it a hard
        # dependency overnight and every design died with ModuleNotFoundError. Installing a 176MB ONNX
        # model into the web container so a machine with no GPU could redo work the machine with one
        # had already done was the wrong half of the problem to solve.
        cut, rep = (br.alpha_cutout(raw, cut_to) if _already_matted(raw)
                    else br.matte_cutout(raw, cut_to))
    else:
        cut, rep = br.key_cutout(raw, cut_to, tol=tol)
    print(f"  kesim: opak %{rep['opaque_frac']*100:.1f}, zemin %{rep['bg_frac']*100:.1f}, "
          f"kalan anahtar %{rep['leftover_frac']*100:.3f} ({rep['leftover_key_px']}px), delik {rep['holes_px']}px, "
          f"acik alan %{rep['pale_field_frac']*100:.0f}, hale %{rep['halo_frac']*100:.2f}, kenar temasi %{rep['edge_contact']*100:.1f}, "
          f"cizim {rep['art_px']}px = 300 PPI'da {rep['size_in_at_300']} inc", file=sys.stderr)
    # Every judgement below is a labelled example with its features already measured. Throwing that away
    # is how a shop arrives at "we should train on our own style" with no data to train on.
    def label(verdict: str, reason: str) -> None:
        design_feedback.record_quietly(
            product_id=p["id"], shop_id=p.get("shop_id"), source="pipeline", verdict=verdict,
            reason=reason, metrics=rep, prompt=(p.get("design_prompt") or "")[:8000],
            design_model=br.DEFAULT_MODEL, attempt=attempt)

    def refuse(gate: str, message: str) -> None:
        label("rejected", f"{gate} {message}")
        raise RuntimeError(message)

    # NON-NEGOTIABLE 5: no AI-rendered text. Every word on a garment is hand-set by typeset.py because
    # models return malformed glyphs — the bake-off that first looked for this found badges reading
    # "EESTOR DUTDER" and "WIRILS · BOGAE", and across 45 generations Juggernaut drew letterforms in 40%
    # of images. ops/text_gate.py was written as the backstop and then wired to nothing, so until now the
    # only rule the shop calls absolute was the one rule production never checked. The OCR runs on the
    # Spark, which has it; this is where the answer is acted on.
    #
    # A missing measurement is not a clean image. It is only tolerated because the hosted path has no
    # OCR at all and refusing everything there would stop production for a rule it cannot evaluate.
    found = p.get("_text_found")
    if found:
        refuse("yazi", f"model harf cizdi ({', '.join(sorted(set(found))[:6])}) — "
                       "yazi elle diziliyor, yeniden cizilecek")

    if rep["bg_frac"] < 0.15:
        refuse("bg", 
            f"anahtar renk zemin bulunamadi (zemin %{rep['bg_frac']*100:.1f}) — generator istenen "
            f"{br.KEY_COLOR} arka plani cizmemis; prompt/urun kontrol edilmeli")
    # As a SHARE of the artwork. 200 pixels was never calibrated — it guarded a metric that always returned
    # 0 — and on a 3000px print 300 stray pixels is a speck, while on a small patch it is dirt. Measured
    # across 215 shipped files the median is 0 and the 99th percentile 143 absolute; 0.2% of the opaque
    # area sits far above the norm and far below anything visible.
    if rep["leftover_frac"] > 0.002:
        refuse("leftover", f"kesimden sonra opak alanin %{rep['leftover_frac']*100:.2f}'i anahtar renkte "
                           f"({rep['leftover_key_px']} piksel) — zemin temizlenemedi, dosya yayina verilmez")
    # A glow or shadow blends ink into the matte over tens of pixels, and those blended pixels sit BEYOND
    # the keying tolerance, so they survive as bright magenta ink while every distance-based check reports
    # clean. Hue sees it. Threshold is 0.2% of the opaque area; a synthetic glow measured 20%.
    # Measured over the SILHOUETTE EDGE BAND, not the whole artwork, and calibrated against what has
    # actually shipped: 215 files put the median at 0.00001 and the 90th percentile at 0.011, while a
    # blend ring measures 1.0 — the two populations do not overlap. The tail (ob-c6-v1 at 0.69) is designs
    # whose OUTLINE is pink, which the palette now forbids outright, so on new work any magenta in the edge
    # band is a blend artefact by construction.
    if rep["halo_frac"] > 0.5:
        refuse("halo", f"silueti saran seridin %{rep['halo_frac']*100:.0f}'i anahtar renk tonunda — "
                           "kenarda magenta hale var (yumusak parlama/golge zemine karismis), "
                           "dosya yayina verilmez")
    # The artwork used the key colour itself, so the cut removed it and left a hole THROUGH the design.
    # 36 concepts in this catalogue ask for pink or magenta in their own palette.
    # As a SHARE, like every other threshold here. 2000 absolute was another uncalibrated number: on a
    # 2880px canvas a real generation returned 3357 hole pixels, which is 0.06% of the artwork — speckle
    # from anti-aliasing where an ink edge grazed the keying band, not a hole through the design. A hole
    # that matters is a visible gap.
    if rep["holes_frac"] > 0.005:
        refuse("holes", f"tasarimin icinde {rep['holes_px']} piksellik kapali delik var — cizimin kendisi "
                           f"anahtar rengi ({br.KEY_COLOR}) kullanmis ve kesimde delinmis; konseptin "
                           "paletinden pembe/magenta cikarilmali")
    # The sticker plate, as a BACKSTOP only. Calibrated against the catalogue rather than against the
    # docstring's remembered "median 3.1%", which is wrong: measured over 214 files the median is 20.8%
    # and the 95th percentile 62%. This shop's designs are cream-heavy, so paleness cannot separate "a
    # cream design" from "a cream plate" and a gate at 30% would refuse half the catalogue. The real fix
    # for the empty plaque is upstream — strip_caption_talk removes the concept's own "leave a blank
    # headline area" instruction when the product has no words. This only catches the extreme.
    if rep["pale_field_frac"] > 0.70:
        refuse("pale_field", f"tasarimin %{rep['pale_field_frac']*100:.0f}'i acik renk duz alan — arkada "
                           "krem plaka var (bos baslik alani cizilmis olabilir), koyu gomlekte sticker "
                           "gibi durur; dosya yayina verilmez")
    if not 0.03 <= rep["opaque_frac"] <= 0.95:
        refuse("opaque", f"opak alan %{rep['opaque_frac']*100:.1f} — tasarim ya kayboldu ya zemin kaldi")
    # Artwork on the border means the composition ran off the canvas. It is invisible in the raw frame and
    # unmissable on a tee, where a wing or a boot ends in a straight cut. Same treatment as a failed cut:
    # the caller regenerates once. Measured on ~bg now rather than on the eroded mask, which was
    # always 0 — so the threshold is 6%, wide enough for a design that legitimately reaches toward an edge
    # and narrow enough to catch a band running clean across it.
    if rep["edge_contact"] > 0.06:
        refuse("edge_contact", f"tasarim kenara degiyor (%{rep['edge_contact']*100:.1f}) — kompozisyon "
                           "canvas disina tasmis, kirpilmis dosya baskiya verilmez")
    # Not fatal: a short file still prints, just softer. Say it out loud rather than shipping quietly under
    # standard, because nothing downstream measures this again.
    # The floor is what this design is actually printed at, not a fixed ten inches. A 4 inch left-chest icon
    # needs 1200 px and demanding 2850 of it would be a warning we learn to ignore; a full-front print still
    # has to carry its full size. The design declares the size, and the file is measured against that.
    import produce_images as pi                     # noqa: PLC0415 — only this check needs the placement
    want_in = pi.print_placement(p.get("design_params"))["inches"]
    if rep["size_in_at_300"] < want_in * 0.95:
        print(f"  UYARI dosya 300 PPI'da {rep['size_in_at_300']} inc basilabilir ama tasarim "
              f"{want_in:g} inc icin isaretli — daha buyuk uretilmeli", file=sys.stderr)
    if p["technique"] == "embroidery" and p["thread_colors"]:
        br.stage_palette_snap(cut, br.hexes(p["thread_colors"]), final)
    else:
        final.write_bytes(Path(cut).read_bytes())
    # Every gate passed. The positive half of the dataset — without it the record only ever learns what
    # a bad design looks like.
    label("accepted", "tum kapilar gecti")
    return final


# Example values for the placeholders a personalised hook carries. 67 hooks hold tokens like {SURNAME} or
# {GRADE}, and a listing image is the one place they must NOT appear literally: 22 products once shipped
# reading "[Name]'S DAD". The buyer's real value is set per order; the listing shows a plausible example so
# they can see what they are buying.
EXAMPLES = {
    "NAME": "EMMA", "NAMES": "EMMA, NOAH & MIA", "NAME1": "EMMA", "NAME2": "NOAH",
    "SURNAME": "MILLER", "YEAR": "2026", "GRADE": "2ND GRADE", "ROOM": "12",
    "TEACHERNAME": "MRS. HAYES", "PETNAME": "BISCUIT", "SUBJECT": "SCIENCE",
}
PLACEHOLDER = re.compile(r"[{\[]([^}\]]+)[}\]]")


def fill_placeholders(text: str) -> str:
    """Swap {TOKEN} for an example. An unknown token becomes a neutral word rather than braces on a shirt."""
    return PLACEHOLDER.sub(lambda m: EXAMPLES.get(m.group(1).strip().upper(), "YOURS"), text)


def pick_garment(art_path: Path) -> tuple[str, str, float]:
    """Choose the hero garment for this artwork, and the ink the type must be set in.

    Returns (colourway, ink hex). The garment is whichever model blank the artwork reads most strongly
    against; the ink is then simply the opposite end of the scale from that garment.
    """
    import numpy as np
    c = conn(); k = c.cursor()
    k.execute("SELECT colorway, bytes FROM mockup_blanks WHERE name = ANY(%s)",
              (["model-IvoryTrendy4", "model-Pepper"],))
    blanks = [(cw, Image.open(io.BytesIO(bytes(b))).convert("L")) for cw, b in k.fetchall()]
    c.close()
    a = np.asarray(Image.open(art_path).convert("RGBA"))
    m = a[:, :, 3] > 128
    if not m.any() or not blanks:
        return "Ivory", "#2B2B2B", 247.0
    ink_lum = float((0.2126 * a[:, :, 0] + 0.7152 * a[:, :, 1] + 0.0722 * a[:, :, 2])[m].mean())
    best = max(blanks, key=lambda t: abs(ink_lum - float(np.asarray(t[1]).mean())))
    garment_lum = float(np.asarray(best[1]).mean())
    ink = "#F2E8D5" if garment_lum < 128 else "#2B2B2B"
    print(f"  garment {best[0]} secildi (tasarim {ink_lum:.0f}, kumas {garment_lum:.0f}); "
          f"yazi {ink}", file=sys.stderr)
    return best[0], ink, garment_lum


def dominant_ink(art_path: Path) -> str:
    """The artwork's own main ink colour, for the caption to be set in.

    The winners set the caption in the SAME colour as the illustration: cream type under a cream engraving,
    dark type under a dark one. Deciding from median luminance failed on exactly the style we now default to
    — an engraving is cream fills over dark hatching, so the median reads "dark" while the design reads
    light, and the caption came out invisible on the garment the artwork needs. Taking the most common
    colour instead follows the artwork rather than an average of it.
    """
    import numpy as np
    a = np.asarray(Image.open(art_path).convert("RGBA"))
    m = a[:, :, 3] > 200
    if not m.any():
        return "#2B2B2B"
    px = a[:, :, :3][m]
    # Quantise so near-identical inks count as one, and ignore the thin outline black that borders
    # everything: it is structure, not the design's colour.
    q = (px // 24) * 24
    lum = 0.2126 * q[:, 0] + 0.7152 * q[:, 1] + 0.0722 * q[:, 2]
    keep = q[(lum > 28) & (lum < 250)]
    if not len(keep):
        keep = q
    colours, counts = np.unique(keep, axis=0, return_counts=True)
    r, g, b = colours[counts.argmax()]
    # Nudge toward the warm cream / charcoal the shop prints, so type stays in the house palette.
    return "#F2E8D5" if (0.2126 * r + 0.7152 * g + 0.0722 * b) > 150 else "#2B2B2B"


def set_type(p: dict, art_path: Path, work: Path) -> Path:
    """Hand-set the product's phrase onto the artwork.

    Every design that sells carries words, and ours went out as wordless emblems. The model never draws
    letters — it returns malformed glyphs — so the phrase is set here in real type, in the layout its
    style calls for (serif caption under an engraving, arched title over a character, poster stack).

    The ink follows the ARTWORK, not the stored hero colourway. That ordering matters: the garment is
    chosen later, by measured contrast against this same artwork, so a cream-forward engraving will end up
    on a dark tee. Reading `hero_colorway` here would have set dark type for the Ivory in the row and then
    put it on the Pepper the contrast rule picks — invisible text on a listing that looked finished.
    Matching the artwork's own ink keeps the two decisions consistent whichever garment wins.
    """
    hook = (p.get("hook") or "").strip()
    if not hook:
        return art_path                      # a wordless design is valid, just weaker
    hook = fill_placeholders(hook)
    style = (p.get("design_params") or {}).get("style") if isinstance(p.get("design_params"), dict) else None

    garment, ink, garment_lum = pick_garment(art_path)
    # Record it now so produce_images features the same garment the type was set for.
    c = conn(); k = c.cursor()
    k.execute("UPDATE products SET hero_colorway=%s WHERE id=%s", (garment, p["id"]))
    c.commit(); c.close()

    out = work / f"{p['slug']}-typed.png"
    canvas, drawn, type_mask = typeset.compose(Image.open(art_path), hook,
                                               style=style or "engraving", ink=ink, size=PRINT_PX)
    if not drawn:
        return art_path

    # Measure what was actually drawn, not what was asked for. A product shipped with a dark caption on a
    # Pepper hero — unreadable — while the log for that very run reported cream ink. I could not reproduce
    # the divergence (typeset honours the ink it is given, verified both ways), so this checks the OUTPUT
    # instead of trusting the decision: if the caption does not separate from the garment it will sit on,
    # set it again in the opposite ink and say so.
    canvas, ink = _ensure_readable(canvas, type_mask, art_path, hook, style, ink, garment_lum)

    canvas.save(out)
    print(f"  yazi dizildi: {drawn} satir, murekkep {ink}", file=sys.stderr)
    return out


def _caption_lum(canvas: Image.Image, type_mask: Image.Image) -> float | None:
    """Mean luminance of the type, measured through the mask typeset drew it with."""
    import numpy as np
    a = np.asarray(canvas.convert("RGBA")).astype(float)
    m = np.asarray(type_mask) > 128
    if m.sum() < 200:                         # no measurable type: nothing to judge
        return None
    return float((0.2126 * a[:, :, 0] + 0.7152 * a[:, :, 1] + 0.0722 * a[:, :, 2])[m].mean())


def _ensure_readable(canvas: Image.Image, type_mask: Image.Image, art_path: Path, hook: str,
                     style: str | None, ink: str, garment_lum: float,
                     floor: float = 100.0) -> tuple[Image.Image, str]:
    """Re-set the type in the opposite ink when it would not read on the chosen garment.

    The floor is 100, not the ~60 a pure luminance difference would suggest. Dark type on Pepper measures
    a difference of 84 and is still unreadable on the finished mockup: the compositor multiplies the ink by
    the garment's shading and lays it at 0.94 opacity, and thin serif strokes lose far more separation than
    a flat tone comparison predicts — this is the exact case that shipped an invisible caption.

    With only two hero blanks (Ivory 247, Pepper 127) this floor reduces to a rule the pipeline already
    intends: dark garment gets cream type, light garment gets dark. So the gate adds no new policy — it
    catches any path that produced something else, which is what happened and what I could not reproduce.
    """
    lum = _caption_lum(canvas, type_mask)
    if lum is None:
        return canvas, ink
    contrast = abs(lum - garment_lum)
    if contrast >= floor:
        return canvas, ink
    flipped = "#2B2B2B" if garment_lum >= 128 else "#F2E8D5"
    print(f"  UYARI yazi kumasa karsi okunmuyor (yazi {lum:.0f} vs kumas {garment_lum:.0f}, "
          f"kontrast {contrast:.0f} < {floor:.0f}) — murekkep {flipped} ile tekrar diziliyor",
          file=sys.stderr)
    again, _, _ = typeset.compose(Image.open(art_path), hook, style=style or "engraving",
                                  ink=flipped, size=PRINT_PX)
    return again, flipped


# 10 inches at 300 PPI, which is the print the producer lays down.
#
# typeset.compose defaults to a 2048 px canvas, and produce_product accepted that default from the day
# it was written: every design whose hook got typeset shipped a 2048 px print file — 205 PPI across a
# 10 inch chest, a fifth short of the floor stated in the standards and enforced on the cutout two
# stages earlier. The gate never caught it because the gate measures the CUTOUT (3031 px, 10.1 inches
# at 300) while the file stored for the producer is the typeset canvas. Wordless designs were fine and
# hid the pattern: they skip compose entirely and keep the full-resolution cutout, which is why the
# catalogue reads 2880 and 3000 almost everywhere and 2048 only where a slogan was set.
#
# Everything inside compose is a fraction of the canvas, so a larger number changes resolution and
# nothing else about the composition.
PRINT_PX = 3000


def store_print_file(p: dict, art: Path) -> None:
    blob = art.read_bytes()
    w, h = Image.open(art).size
    c = conn(); k = c.cursor()
    # print_dpi was left null by this path, so the one column that says what the file is FOR carried
    # nothing on every product it produced — and a print file without its intended resolution is just
    # a picture.
    k.execute("""UPDATE products SET print_file=%s, print_file_name=%s, print_file_w=%s,
                        print_file_h=%s, print_dpi=300, design_state='generating', updated_at=now()
                  WHERE id=%s""",
              (psycopg2.Binary(blob), f"{p['slug']}-print.png", w, h, p["id"]))
    c.commit(); c.close()


def build_images(pid: int, only_cover: bool = False) -> int:
    cmd = [sys.executable, str(HERE / "produce_images.py"), str(pid)]
    if only_cover:
        cmd.append("--only-cover")
    r = subprocess.run(cmd,
                       capture_output=True, text=True)
    last = (r.stdout or r.stderr or "").strip().splitlines()[-1:] or [""]
    try:
        out = json.loads(last[0])
    except json.JSONDecodeError:
        raise RuntimeError(f"produce_images: {last[0][:200]}")
    if not out.get("ok"):
        raise RuntimeError(f"produce_images: {last[0][:200]}")
    return int(out.get("images", 0))


def set_state(pid: int, state: str) -> None:
    c = conn(); k = c.cursor()
    k.execute("UPDATE products SET design_state=%s, updated_at=now() WHERE id=%s", (state, pid))
    c.commit(); c.close()


def mark_ready(pid: int) -> None:
    c = conn(); k = c.cursor()
    k.execute("UPDATE products SET design_state='ready', updated_at=now() WHERE id=%s", (pid,))
    c.commit(); c.close()


def produce(pid: int, redo: bool = False, stage: str = "all") -> dict:
    """Build (or rebuild) one product's artwork and listing images.

    `redo` clears the existing print file and images so the design is drawn again — and it does that HERE,
    after the approval check, on purpose. Callers used to clear first and then invoke this, which meant an
    unapproved product had its artwork deleted and then the refusal arrived: nine draft products lost their
    print file and every listing image that way, with nothing left to rebuild from. The destructive step
    belongs behind the guard that decides whether the work can happen at all.
    """
    p = load(pid)
    if p["content_status"] != "approved":
        return {"ok": False, "slug": p["slug"], "error": f"content_status={p['content_status']}, onayli degil"}
    # Embroidery is paused for NEW products (operator, 2026-08-15): it stays on sweatshirts and comes off
    # t-shirts. The 37 that exist keep running — this refuses to DRAW a new one, which is where the money
    # goes, rather than touching anything already made. `has_print` is the test for "already made": a
    # product with a file is being rebuilt, not created.
    if p["technique"] == "embroidery" and not p["has_print"] and not EMB_OK.search(str(p.get("blank") or "")):
        return {"ok": False, "slug": p["slug"],
                "error": f"nakis yeni urunlerde durduruldu — blank '{p.get('blank')}' sweatshirt degil. "
                         f"Mevcut nakis urunler calismaya devam eder; yeni nakis icin sweatshirt blank sec."}
    if redo:
        c = conn(); k = c.cursor()
        k.execute("""UPDATE products SET print_file=NULL, design_state=NULL, redo_note=NULL
                      WHERE id=%s""", (pid,))
        k.execute("DELETE FROM product_images WHERE product_id=%s", (pid,))
        c.commit(); c.close()
        p = load(pid)                     # has_print is now false; generate from scratch

    with Job("design", f"{p['slug']} · tasarim + gorseller", total=3, shop_id=p["shop_id"],
             product_id=pid) as job:
        with tempfile.TemporaryDirectory(prefix=f"prod-{p['slug']}-") as tmp:
            work = Path(tmp)
            if not p["has_print"]:
                # The generator honours the key colour most of the time, not every time — measured, it
                # painted magenta on one attempt and something else on another with the same prompt. A
                # stochastic miss should cost a second call, not the operator's afternoon, so the gate's
                # verdict drives one retry before it becomes an error.
                #
                # BEST-OF-N. The loop used to stop at the first draw that was merely ALLOWED, which treats
                # a design scraping past every gate and one comfortably clear of all of them as the same
                # product. The generator is stochastic, so another draw is a different design for the
                # price of one call — DESIGN_BEST_OF=3 buys the pick instead of the first pass. Default
                # stays 1: this doubles or triples the paid step and that is the operator's decision, not
                # a default someone discovers on an invoice.
                art = None
                best = (-1.0, None, None)
                want_in = pi_mod.print_placement(p.get("design_params"))["inches"]
                last_err: RuntimeError | None = None
                for attempt in range(1, BEST_OF + 2):
                    # The extra attempt past BEST_OF is the retry for a stochastic miss: it only runs if
                    # nothing has passed yet, and it is the one that narrows the tolerance and shouts
                    # about magenta.
                    retrying = attempt > BEST_OF or HARD_MODE
                    if retrying and best[1] is not None:
                        break
                    raw = generate(p, work, tag=f"a{attempt}")
                    job.tick("tasarim uretildi" if attempt == 1 else "tasarim tekrar uretildi")
                    try:
                        cand = cutout(p, raw, work, tol=TOL_TIGHT if retrying else TOL_WIDE,
                                      attempt=attempt, tag=f"a{attempt}")
                    except RuntimeError as e:
                        last_err = e
                        print(f"  UYARI kesim reddetti ({e})", file=sys.stderr)
                        raw.unlink(missing_ok=True)
                        continue
                    pts, parts = design_score.score_file(cand.read_bytes(), want_in)
                    print(f"  aday a{attempt}: {pts}/100 {parts}", file=sys.stderr)
                    if pts > best[0]:
                        best = (pts, cand, parts)
                if best[1] is None:
                    raise last_err or RuntimeError("hicbir aday kapilari gecemedi")
                art = best[1]
                if BEST_OF > 1:
                    print(f"  secilen: {best[0]}/100", file=sys.stderr)
                job.tick("arka plan temizlendi")
                # Embroidery is typeset by the generator, not by us. print_file for an embroidery
                # product is the digitiser's spec — flat colour, exact thread hexes — and its hook is a
                # descriptive sentence ("a stone dice tower crowned as a guild badge"), not a slogan.
                # Laying PIL type over it would hand the factory a paragraph to stitch, and the listing
                # would never show it either: the gallery composites emb_render, not print_file.
                if p["technique"] != "embroidery":
                    art = set_type(p, art, work)
                else:
                    print("  nakis: yazi dizilmedi (print_file dijitizasyon spesifikasyonu)", file=sys.stderr)
                store_print_file(p, art)
            else:
                job.tick("print_file zaten var")
                job.tick("arka plan atlandi")
            # Two stages, because approval is worth money. "artwork" stops at a design the operator can
            # look at — the print file plus a lead shot and a close crop, about twenty seconds of
            # compositing. "finish" buys the other eight frames and the schedule slot, and only runs on
            # something a human said yes to. Producing thirty designs to the end and asking afterwards is
            # how a rejected style costs half an hour of composites.
            if stage == "artwork":
                n = build_images(pid, only_cover=True)
                job.tick(f"{n} onizleme gorseli")
                set_state(pid, "awaiting_approval")
                return {"ok": True, "slug": p["slug"], "images": n, "stage": "artwork",
                        "state": "awaiting_approval"}
            n = build_images(pid)
            job.tick(f"{n} ilan gorseli")
    mark_ready(pid)
    return {"ok": True, "slug": p["slug"], "images": n}


def main() -> None:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    redo = "--redo" in sys.argv
    stage = "artwork" if "--artwork" in sys.argv else "finish" if "--finish" in sys.argv else "all"
    if not args:
        sys.exit("kullanim: produce_product.py <product_id> [--redo] [--artwork|--finish]")
    try:
        print(json.dumps(produce(int(args[0]), redo=redo, stage=stage), ensure_ascii=False))
    except Exception as e:
        # The caller is a loop or a chat tool; both need the reason as data, not a traceback — but the
        # message alone is not enough to act on. `ModuleNotFoundError: No module named 'rembg'` was
        # reported four times on 2026-08-19 while a fix aimed at the only import anyone could find was
        # deployed and changed nothing, because nothing in the record said WHERE it was raised. The
        # last frames cost a line and end that guessing.
        import traceback                                           # noqa: PLC0415
        frames = [ln.strip() for ln in traceback.format_exc().splitlines()
                  if ln.strip().startswith("File ")][-3:]
        print(json.dumps({"ok": False, "error": f"{type(e).__name__}: {e}"[:300],
                          "where": " <- ".join(f.replace('File "', "").replace('", line ', ":")
                                               for f in reversed(frames))[:400]},
                         ensure_ascii=False))
        sys.exit(1)


if __name__ == "__main__":
    main()
